# Emulate a get request
GET http://localhost:3000


### Emulate a register request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "password123"
}



### Emulate a login request
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "password123"
}



### Emulate a get request with authorization (protected route)
GET http://localhost:3000/