# Emulate a get request
GET http://localhost:3000


### Emulate a register request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "password123"
}



### Emulate a login request
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "password123"
}



### Emulate a get request with authorization (protected route)
GET http://localhost:3000/jobs
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4NzIyNzI2NCwiZXhwIjoxNzg3MzEzNjY0fQ.4CC8_fGNjP8W1ww2K0Z3T5eSovd7B98UFQNKQfqapKU



### Emulate a post request with authorization (protected route)
POST http://localhost:3000/jobs
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4NzIyNzI2NCwiZXhwIjoxNzg3MzEzNjY0fQ.4CC8_fGNjP8W1ww2K0Z3T5eSovd7B98UFQNKQfqapKU
Content-Type: application/json

{
    "company": "Test Company",
    "jobTitle": "Test Job",
    "jobUrl": "http://test.com/job",
    "status": "Applied"
}



### Emulate a request to update a job with authorization (protected route)
PATCH http://localhost:3000/jobs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4NzIyNzI2NCwiZXhwIjoxNzg3MzEzNjY0fQ.4CC8_fGNjP8W1ww2K0Z3T5eSovd7B98UFQNKQfqapKU
Content-Type: application/json

{
    "status": "Interview"
}

### Emulate a request to delete a job with authorization (protected route)
DELETE http://localhost:3000/jobs/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4NzIyNzI2NCwiZXhwIjoxNzg3MzEzNjY0fQ.4CC8_fGNjP8W1ww2K0Z3T5eSovd7B98UFQNKQfqapKU