version: "3"

services:

  job: 
    build: .
    container_name: job-application
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/job_application
      - NODE_ENV=development
      - JWT_SECRET=new_development_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/job

  db:
    image: postgres:13
    container_name: japplication-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_application
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data        

volumes:
  postgres_data:   